services:
  server:
    container_name: server
    hostname: localhost
    build:
      context: .
      target: final
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PASETO_KEY: "RANDOM WORDS WINTER MACINTOSH PC"
      PORT: 8080
      DATABASE_PASSWORD: scheduler
      DATABASE_USER: scheduler
      DATABASE_PORT: 5432
      DATABASE_DB: schedulerdb
      DATABASE_HOST: postgres 
      RUST_LOG: info
    restart: on-failure
    networks:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine3.18
    hostname: localhost
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "schedulerdb"
      POSTGRES_USER: "scheduler"
      POSTGRES_PASSWORD: "scheduler"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - scheduler-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scheduler -d schedulerdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "scheduler@test.io"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4scheduler"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - postgres

  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter:v0.10.1
    environment:
      DATA_SOURCE_URI: "postgres:5432/schedulerdb?sslmode=disable"
      DATA_SOURCE_USER: "scheduler"
      DATA_SOURCE_PASS: "scheduler"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 500M
    networks:
      - postgres

volumes:
  scheduler-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
