# host 
# https://httpbin:443
http://localhost:8080

# curl options
# --silent
# include reponse headers
--include
# to ignore ssl when working with localhost
# --verbose
# --insecure
# to read a header(s) from a file. File fromat should be like:
# Header-Name: Header-Value
# e.g Authorization: YOUR_AUTH_TOKEN_HERE
# -H @/path/to/file.txt
#
# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# query
POST /registration

#body
{
  "email": "test1@test.iv",
  "password": "passfdsfsf"
}
