# host 
# https://httpbin:443
http://localhost:8080

# curl options
# --silent
# include reponse headers
--include
# to ignore ssl when working with localhost
# --verbose
# --insecure
# to read a header(s) from a file. File fromat should be like:
# Header-Name: Header-Value
Authorization: v2.local.Dd49tswf5HQdrfPur-hL-w61fp8_0sDUtnGlzVvQOKmYjFlWSjXg5Qbctjk9m1szBk8n6AKadP01bVzOTcwAXZg2VB3FAT7vtZF-zbnC-CmHzk5fXb3RpWRQFvDwLl5MNPCvgIkf-yKRNKArD67xJkYlP49pprTHYmF8fppihk_1A3a5a50
# e.g Authorization: YOUR_AUTH_TOKEN_HERE
# -H @/path/to/file.txt
#
# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# query
POST /time_spent

#body
{
  "time": 10,
  "activity_id": 1
}
