# host 
# https://httpbin:443
http://localhost:8080

# curl options
# --silent
# include reponse headers
--include
# to ignore ssl when working with localhost
# --verbose
# --insecure
# to read a header(s) from a file. File fromat should be like:
# Header-Name: Header-Value
Authorization: v2.local.mexYJdYd4DzgSsS5qQeGhGSIF6gTjrip0eteXDXNmT_cXbrGVraD_EHBR5zVCjusNr9V2cnRVytcXtQ_r-NzK8tS9e4xKuRXPNqVosSr9eOtdpyfYzOMCLvKFRJZpoHEncRDWMNozdUyRhLAwus1EUHpaKA2dbQkc4DinBVwVQHIYzk1NdQ
# -H @/path/to/file.txt
#
# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# query
POST /activities

#body
{
  "title": "How",
  "content": "Please help",
  "time": 10
}
